language: python

python:
    - '3.6'

services:
    - docker

addons:
    ssh_known_hosts: ssh.pythonanywhere.com

before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass

install:
    - pip install -r docker/requirements-dev.txt 

env:
    - PYTHONPATH=/home/travis/build/gcallah/CourseBuilder

script:
    - make tests

after_success:
    - ./deploy.sh $pa_pwd


notifications:
  slack: devopsnyu:YZ3A0SLBrYur0DXkEh95c9Y2
