language: python

python:
    - '3.6'

services:
    - docker

addons:
    ssh_known_hosts: ssh.pythonanywhere.com

before_install:
  - openssl aes-256-cbc -K $encrypted_bf55724b916d_key -iv $encrypted_bf55724b916d_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - eval "$(ssh-agent -s)" 
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - chmod 600 ~/.ssh/authorized_keys

install:
    - pip install -r docker/requirements-dev.txt 

env:
    - PYTHONPATH=/home/travis/build/gcallah/CourseBuilder

script:
    - make tests

after_success:
    - ./deploy.sh


notifications:
  slack: devopsnyu:YZ3A0SLBrYur0DXkEh95c9Y2
