language: python

python:
    - '3.6'

services:
    - docker

addons:
    ssh_known_hosts: 

before_install:
    

install:
    - pip install -r docker/requirements-dev.txt 

env:
    - 

script:
    - make tests

after_success:
    - ./deploy.sh

notifications:
  slack: devopsnyu:YZ3A0SLBrYur0DXkEh95c9Y2
