# Generated by Django 2.2.6 on 2019-10-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursebuilder", "0004_auto_20190503_0144")]

    operations = [
        migrations.AlterModelOptions(name="question", options={"ordering": ["module"]})
    ]
