# Generated by Django 2.1.2 on 2019-10-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursebuilder', '0005_auto_20191013_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursebuilder.CourseModule'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursebuilder.CourseModule'),
        ),
    ]
