# Generated by Django 2.1.2 on 2019-10-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursebuilder", "0007_auto_20191025_0314")]

    operations = [
        migrations.AlterModelOptions(
            name="extras", options={"verbose_name_plural": "Extras"}
        )
    ]
