# Generated by Django 2.1.2 on 2019-10-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("coursebuilder", "0008_auto_20191025_0316")]

    operations = [
        migrations.AlterModelOptions(
            name="quiz", options={"verbose_name_plural": "Quizzes"}
        )
    ]
