# Generated by Django 2.2.8 on 2019-12-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("coursebuilder", "0009_auto_20191025_0347")]

    operations = [
        migrations.AlterModelOptions(
            name="coursemodule", options={"ordering": ["course_order"]}
        ),
        migrations.AlterModelOptions(
            name="modulesection", options={"ordering": ["module", "order"]}
        ),
        migrations.AlterModelOptions(
            name="question", options={"ordering": ["module", "qtype", "difficulty"]}
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="course_order",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="modulesection", unique_together={("module", "order")}
        ),
    ]
